### ISSUE TITLE
WRT1900ACS

### ISSUE THREAD

**Issue by SeattleRex** [wrt1900ac/opensource#16]
There is a "new version" of this router (released October 8, 2015), called the WRT1900ACS.  I purchased this router last week.

In looking for opensource firmware, I see a few offerings for the WRT1900AC, but not much for the 1900ACS ... which makes sense given it's age.

That being said, the main changes between the AC and ACS are (from what I understand) little more than a CPU speed increase from 1.2/1.3Ghz to 1.6Ghz, plus a RAM doubling from 256M to 512M.  If all else is the same, I imagine the 1900AC firmware would work for it.

Does anyone know if this is, indeed the case?

Thanks for creating this project.

**Comment by notnyt** [comment]
This isn't a driver bug, so this is not the appropriate place for this.  I suggest reading the thread on the openwrt forums.

https://forum.openwrt.org/viewtopic.php?id=50173

**Comment by Chadster766** [comment]
Instead I recommend this link:
http://wiki.openwrt.org/toh/linksys/wrt1900ac
