### ISSUE TITLE
Repo not available

### ISSUE THREAD

**Issue by jklap** [wrt1900ac/opensource#4]
Referenced repo: https://github.com/jimmychungbelkin/Mamba

Does not seem to be public. Can you please review?

**Comment by jimmychungbelkin** [comment]
Mambe repo is a private repo.
You will have to send us email with your github ID to provide access.

**Comment by notnyt** [comment]
Please add this user

**Comment by jklap** [comment]
Thanks Jimmy,

Would you please add this user?

**Comment by jimmychungbelkin** [comment]
you mean add: jklap ??
Please send the Github ID of the user to be added

**Comment by notnyt** [comment]
Yes, please add the users requesting.

notnyt
jklap

**Comment by jimmychungbelkin** [comment]
Guys,
Can you please send us email about this to me and Jimmy. Need that to keep track of these requests.
Thanks

**Comment by jklap** [comment]
Sure-- what email address do you want them sent to?

**Comment by DrakiaXYZ** [comment]
Any particular reason the repository containing the OpenWRT code is marked as private? Seems rather against the open-source nature of OpenWRT and what Linksys has been saying about this router since it was announced.

Either way, I would also like to know what email address to send to to gain access.

**Comment by DrakiaXYZ** [comment]
Can we get an update on this? 
What email address are we supposed to email to gain access?
And why is the GPL'd code for a publicly distributed binary build even in a private repo to begin with?

**Comment by wrt1900ac** [comment]
Hello, 
https://github.com/jimmychungbelkin/Mamba is now publicly accessible.  Thank you.
