### ISSUE TITLE
Build tree not accessible

### ISSUE THREAD

**Issue by DrakiaXYZ** [wrt1900ac/opensource#6]
The linked GitHub repo for the build tree (https://github.com/jimmychungbelkin/Mamba) is not accessible.

**Comment by cemeyer2** [comment]
I do not think it is responsible to be distributing code that is claimed to be open source if it turns out that it is not. Please explain why that repository is private

**Comment by cemeyer2** [comment]
How do we know that the code being built and posted does not contain anything nefarious? I would highly suggest no one install these binaries on their routers until we can verify that the code that makes up those builds is secure and safe. We cannot do that until the source tree is made available to all.

**Comment by jimmychungbelkin** [comment]
Hello, 
https://github.com/jimmychungbelkin/Mamba is now publicly accessible. Thank you.
